### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by vishalvaishnav2405** [farhan123806/Breast-Cancer-Detection-By-using-Deep-Learning#2]
hi farhan there are still some issues in the BCD can we have a meet to  solve the issue ??

**Comment by vishalvaishnav2405** [comment]
Hi farhaan there is still some issue in the breast cancer code, can u please help

**Comment by farhan123806** [comment]
Yeah sure, I would love to resolve the issue, please drop out the details of meet up and decide a date so I can make myself available on that day

**Comment by vishalvaishnav2405** [comment]
Sorry for the late reply. Can we do a meet on Wednesday after 4 pm ?? (Meet link: https://meet.google.com/fjk-ztty-ciq)  contact me on this mail id :- vishalvaishnav2405@gmail.com

**Comment by vishalvaishnav2405** [comment]
Hi farhan hope you have a good day. Can we do a meet on Wednesday after 4 pm ?

**Comment by vishalvaishnav2405** [comment]
> Yeah sure, I would love to resolve the issue, please drop out the details of meet up and decide a date so I can make myself available on that day

Thank you farhan for yhe reply. Can have meet on 8th march??
